# Generated by Django 6.0.3 on 2026-04-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0002_genre_book_isbn_book_pages_book_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='0000', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0),
        ),
    ]
