# Generated by Django 6.0.3 on 2026-04-20 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0003_alter_book_isbn_alter_book_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumary', models.TextField()),
                ('cover_url', models.CharField()),
                ('language', models.CharField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='minilibrary.book')),
            ],
        ),
    ]
