# Generated by Django 6.0.3 on 2026-04-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0004_bookdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdetail',
            old_name='sumary',
            new_name='summary',
        ),
    ]
