# Generated by Django 6.0.3 on 2026-04-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0006_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
